#! /bin/bash
  
set -e

if [ $# -ne 2 ]
then
  echo "You need two arguments [Molecule] [Basis] !!" 
fi

if [ $# = 2 ]
then
  cp examples/molecule."$1"   input/molecule
  cp examples/basis."$1"."$2" input/basis
  cp basis/"$2"               input/basis.qcaml
#  ./bin/IntPak
  ./bin/QuAcK
fi

