#! /bin/bash

cp input/molecule.Hu input/molecule
cp input/basis.Hu    input/basis
cp int/nBas.Hu.dat   int/nBas.dat
cp int/ERI.Hu.dat    int/ERI.dat
cp int/Kin.Hu.dat    int/Kin.dat
cp int/Nuc.Hu.dat    int/Nuc.dat
cp int/Ov.Hu.dat     int/Ov.dat
cp int/x.Hu.dat      int/x.dat
cp int/y.Hu.dat      int/y.dat
cp int/z.Hu.dat      int/z.dat
./bin/QuAcK
