#! /bin/bash

if [ $# -ne 2 ]
then
  echo "You need two arguments [Number of electrons] [BasisSetSize] !!" 
fi

if [ $# = 2 ]
then
cp examples/molecule.Sph_"$1"  input/molecule
cp examples/basis.Sph.Ylm"$2" input/basis
cp ~/Integrals/QuAcK_Sph/Sph_ERI_"$2".dat int/ERI.dat
cp ~/Integrals/QuAcK_Sph/Sph_Kin_"$2".dat int/Kin.dat
cp ~/Integrals/QuAcK_Sph/Sph_Nuc_"$2".dat int/Nuc.dat
cp ~/Integrals/QuAcK_Sph/Sph_Ov_"$2".dat  int/Ov.dat
./bin/QuAcK
fi
