#! /bin/bash

if [ $# -lt 2 ]
then
  echo "At least 2 arguments required [Molecule] [Basis] [AuxBasis] !!" 
fi
if [ $# = 2 ]
then
  cp molecule."$1"  ../input/molecule
  cp basis."$1"."$2"  ../input/basis
elif [ $# = 3 ]
then
  cp molecule."$1"  ../input/molecule
  cp basis."$1"."$2"  ../input/basis
  cp auxbasis."$1"."$3"  ../input/auxbasis
fi

