IDIR =$(QUACK_ROOT)/include

FC = gfortran -I$(IDIR) -J$(IDIR) 
#FC = ifort -I$(IDIR)  -module $(IDIR)
AR = libtool

ifeq ($(DEBUG),1)
FFLAGS = -Wall -g -msse4.2 -fcheck=all -Waliasing -Wampersand -Wconversion -Wsurprising -Wintrinsics-std -Wno-tabs -Wintrinsic-shadow -Wline-truncation -Wreal-q-constant
else
FFLAGS = -Wall -Wno-unused -Wno-unused-dummy-argument -O3
endif

